package portalserver

import (
	"bytes"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/davidpopovici01/grades/internal/portalauth"
)

// Reserved identity for the built-in demo account. Negative IDs can never be
// generated by the CLI's autoincrement tables, which keeps demo data out of
// every publish-cleanup path (remapStudentIDs skips negative IDs).
const (
	demoUsername     = "demo"
	demoStudentID    = -1
	demoCourseYearID = -1
	demoTermID       = -1
)

//go:embed demo_materials/syllabus.md
var demoSyllabus []byte

//go:embed demo_materials/getting-started.md
var demoGettingStarted []byte

// demoSnapshotJSON is the published grade snapshot for the demo account,
// matching the portalStudentSnapshot shape the CLI builds in
// internal/app/web.go.
const demoSnapshotJSON = `{
  "studentId": -1,
  "firstName": "Demo",
  "lastName": "Student",
  "courseName": "Sample APCSA",
  "termName": "Term 1",
  "sections": ["Demo Section"],
  "username": "demo",
  "weightedTotal": 71.5,
  "weightedTotalLabel": "71.5%",
  "letterGrade": "C-",
  "gpa": 71.5,
  "gpaLabel": "71.5%",
  "activeCategoryCount": 3,
  "overviewCutoffAssignmentId": 0,
  "categories": [
    {
      "categoryId": 1,
      "categoryName": "Quizzes",
      "weightPercent": 20,
      "hasWeight": true,
      "weightLabel": "20.0%",
      "score": 78.5,
      "scoreLabel": "78.5%",
      "schemeKey": "average",
      "included": true,
      "showInOverview": true,
      "dropLowest": 1
    },
    {
      "categoryId": 2,
      "categoryName": "Labs",
      "weightPercent": 40,
      "hasWeight": true,
      "weightLabel": "40.0%",
      "score": 47.5,
      "scoreLabel": "47.5%",
      "schemeKey": "completion",
      "defaultPassPercent": 70,
      "included": true,
      "showInOverview": true
    },
    {
      "categoryId": 3,
      "categoryName": "Tests",
      "weightPercent": 40,
      "hasWeight": true,
      "weightLabel": "40.0%",
      "score": 92,
      "scoreLabel": "92.0%",
      "schemeKey": "average",
      "included": true,
      "showInOverview": true
    }
  ],
  "assignments": [
    {
      "assignmentId": 1,
      "title": "Quiz 1: Variables and Types",
      "categoryId": 1,
      "categoryName": "Quizzes",
      "maxPoints": 100,
      "schemeKey": "average",
      "anchor": 100,
      "lift": 1,
      "score": 85,
      "flags": [],
      "isBeforeCutoff": false,
      "currentPercent": 85,
      "currentPercentLabel": "85.0%",
      "showInOverview": true
    },
    {
      "assignmentId": 2,
      "title": "Quiz 2: Control Flow",
      "categoryId": 1,
      "categoryName": "Quizzes",
      "maxPoints": 100,
      "schemeKey": "average",
      "anchor": 100,
      "lift": 1,
      "score": 72,
      "flags": [],
      "isBeforeCutoff": false,
      "currentPercent": 72,
      "currentPercentLabel": "72.0%",
      "showInOverview": true
    },
    {
      "assignmentId": 3,
      "title": "Quiz 3: Methods",
      "categoryId": 1,
      "categoryName": "Quizzes",
      "maxPoints": 100,
      "schemeKey": "average",
      "anchor": 100,
      "lift": 1,
      "score": 40,
      "flags": [],
      "isBeforeCutoff": false,
      "currentPercent": 40,
      "currentPercentLabel": "40.0%",
      "showInOverview": true,
      "dropped": true
    },
    {
      "assignmentId": 4,
      "title": "Lab 1: Hello Objects",
      "categoryId": 2,
      "categoryName": "Labs",
      "maxPoints": 10,
      "schemeKey": "completion",
      "passPercent": 70,
      "anchor": 100,
      "lift": 1,
      "score": 10,
      "flags": [],
      "isBeforeCutoff": false,
      "currentPercent": 100,
      "currentPercentLabel": "100.0%",
      "showInOverview": true
    },
    {
      "assignmentId": 5,
      "title": "Lab 2: String Methods",
      "categoryId": 2,
      "categoryName": "Labs",
      "maxPoints": 10,
      "schemeKey": "completion",
      "passPercent": 70,
      "anchor": 100,
      "lift": 1,
      "score": 0,
      "flags": ["missing"],
      "isBeforeCutoff": false,
      "currentPercent": 0,
      "currentPercentLabel": "0.0%",
      "showInOverview": true
    },
    {
      "assignmentId": 6,
      "title": "Lab 3: Conditionals",
      "categoryId": 2,
      "categoryName": "Labs",
      "maxPoints": 10,
      "schemeKey": "completion",
      "passPercent": 70,
      "anchor": 100,
      "lift": 1,
      "score": 5,
      "flags": ["redo"],
      "isBeforeCutoff": false,
      "currentPercent": 0,
      "currentPercentLabel": "0.0%",
      "showInOverview": true
    },
    {
      "assignmentId": 7,
      "title": "Lab 4: Loops",
      "categoryId": 2,
      "categoryName": "Labs",
      "maxPoints": 10,
      "schemeKey": "completion",
      "passPercent": 70,
      "anchor": 100,
      "lift": 1,
      "score": 10,
      "flags": ["late"],
      "isBeforeCutoff": false,
      "currentPercent": 90,
      "currentPercentLabel": "90.0%",
      "showInOverview": true
    },
    {
      "assignmentId": 8,
      "title": "Unit 1 Test",
      "categoryId": 3,
      "categoryName": "Tests",
      "maxPoints": 100,
      "schemeKey": "average",
      "anchor": 100,
      "lift": 1,
      "score": 92,
      "flags": [],
      "isBeforeCutoff": false,
      "currentPercent": 92,
      "currentPercentLabel": "92.0%",
      "showInOverview": true
    }
  ],
  "improvementTips": [
    "Finish missing work: Lab 2: String Methods",
    "Redo and resubmit: Lab 3: Conditionals",
    "Focus first on your lowest active category: Labs"
  ]
}`

const demoAssignmentInstructions = "Write a Python program in `grader.py` that reads a list of scores and prints the average.\n\nThis is a sample assignment for exploring the submissions workflow. Submissions are disabled on the demo account."

// SeedDemo upserts the demo account, its sample course, a grade snapshot, and
// one sample submission assignment. It runs on every startup when a demo
// password is configured, so rotating the password takes effect on restart.
func (s *Store) SeedDemo(password string) error {
	hash, salt, err := portalauth.HashPassword(password)
	if err != nil {
		return err
	}
	now := time.Now().UTC().Format(time.RFC3339)
	acc := portalauth.Account{
		StudentID:         demoStudentID,
		Username:          demoUsername,
		PasswordSalt:      salt,
		PasswordHash:      hash,
		PasswordChangedAt: now,
	}
	if err := upsertAccount(s.db, acc); err != nil {
		return err
	}
	if err := upsertCourse(s.db, demoCourseYearID, demoTermID, "Sample APCSA", "2026-27", "Term 1", now); err != nil {
		return err
	}
	if err := upsertStudentSnapshot(s.db, demoStudentID, demoCourseYearID, demoTermID, []byte(demoSnapshotJSON), now); err != nil {
		return err
	}
	_, err = s.db.Exec(`
		INSERT INTO sub_assignments(course_year_id, term_id, title, language, instructions, expected_filenames, is_open)
		SELECT ?, ?, ?, 'python', ?, 'grader.py', 1
		WHERE NOT EXISTS (SELECT 1 FROM sub_assignments WHERE course_year_id = ? AND term_id = ?)`,
		demoCourseYearID, demoTermID, "Sample Python Assignment", demoAssignmentInstructions,
		demoCourseYearID, demoTermID)
	return err
}

// ClearDemo removes every demo row. It runs at startup when no demo password
// is configured, so disabling the demo also disables the loggable account
// instead of leaving it behind with its last-seeded password.
func (s *Store) ClearDemo() error {
	statements := []struct {
		query string
		args  []any
	}{
		{`DELETE FROM published_accounts WHERE student_pk = ?`, []any{demoStudentID}},
		{`DELETE FROM published_students WHERE student_pk = ?`, []any{demoStudentID}},
		{`DELETE FROM published_courses WHERE course_year_id = ? AND term_id = ?`, []any{demoCourseYearID, demoTermID}},
		{`DELETE FROM sub_assignments WHERE course_year_id = ? AND term_id = ?`, []any{demoCourseYearID, demoTermID}},
	}
	for _, stmt := range statements {
		if _, err := s.db.Exec(stmt.query, stmt.args...); err != nil {
			return err
		}
	}
	return nil
}

// seedDemoMaterials writes the sample course's material files next to the real
// course materials. Existing files with identical content are left untouched,
// and _meta.json is written only when missing so admin-UI edits survive.
func (s *Server) seedDemoMaterials() error {
	dir := s.materialsDir(demoCourseYearID, demoTermID, "Sample APCSA")
	unitDir := filepath.Join(dir, "unit-1")
	if err := os.MkdirAll(unitDir, 0o755); err != nil {
		return err
	}
	files := []struct {
		path    string
		content []byte
	}{
		{filepath.Join(unitDir, "syllabus.md"), demoSyllabus},
		{filepath.Join(unitDir, "getting-started.md"), demoGettingStarted},
	}
	for _, f := range files {
		if existing, err := os.ReadFile(f.path); err == nil && bytes.Equal(existing, f.content) {
			continue
		}
		if err := os.WriteFile(f.path, f.content, 0o644); err != nil {
			return fmt.Errorf("failed to write demo material: %w", err)
		}
	}
	metaPath := filepath.Join(dir, courseMetaFile)
	if _, err := os.Stat(metaPath); os.IsNotExist(err) {
		meta := courseMeta{Categories: []categoryMeta{{ID: "unit-1", Name: "Unit 1"}}}
		if err := writeCourseMeta(dir, meta); err != nil {
			return fmt.Errorf("failed to write demo materials metadata: %w", err)
		}
	}
	return nil
}
