package app

import "html/template"

var portalPageTemplate = template.Must(template.New("portal").Parse(`<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{.Title}}</title>
<style>
:root{--bg:#f3efe6;--bg-whatif:#e6f0ec;--paper:#fffdf8;--ink:#1d1c19;--line:#d8d1c6;--teal:#1f5f5b;--gold:#d9a04b;--rose:#8c2c1f;--muted:#625d57}
*{box-sizing:border-box}body{font-family:Georgia,serif;background:linear-gradient(135deg,var(--bg),#ebe6db);color:var(--ink);margin:0}body.what-if{background:linear-gradient(135deg,var(--bg-whatif),#dbe9e3)}
main{max-width:1180px;margin:0 auto;padding:20px}.panel{background:rgba(255,253,248,.97);border:1px solid var(--line);padding:18px;box-shadow:0 10px 24px rgba(0,0,0,.05);height:100%}.hero{display:grid;grid-template-columns:220px 1fr;gap:18px;align-items:stretch}.gpa{background:linear-gradient(160deg,var(--teal),#3b8d87);color:#fff;border:none;display:flex;flex-direction:column;justify-content:center;min-height:170px}.gpa .label{font-size:.95rem;letter-spacing:.08em;text-transform:uppercase;opacity:.88}.gpa .value{font-size:3rem;line-height:1.05;margin-top:10px;font-weight:700}
.gpa .small{margin-top:10px;opacity:.9}.identity h1{margin:0 0 8px}.identity .meta{color:var(--muted);margin:6px 0 0}.identity .strong{font-size:1.35rem}.grid{display:grid;gap:18px;grid-template-columns:repeat(12,1fr);margin-top:18px;align-items:stretch}.span-7{grid-column:span 7}.span-5{grid-column:span 5}.span-12{grid-column:span 12}
input,select,button{width:100%;padding:10px 12px;margin-top:6px;font:inherit;border:1px solid #c9c2b6;background:#fff}button{cursor:pointer;background:var(--teal);color:#fff}button.alt{background:var(--gold);color:#1d1c19}button.ghost{background:#fff;color:var(--teal)}
table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #e5ddd2;padding:8px 6px;text-align:left;vertical-align:top}.error{color:var(--rose);min-height:1.2em}.hidden{display:none}.tip-list{margin:0;padding-left:20px}.tip-list li{margin:6px 0}.notice{background:#fff3df;border:1px solid #e7c78c;padding:12px}.page-actions{display:flex;gap:10px;flex-wrap:wrap}.page-actions a{text-decoration:none}.banner{padding:12px;font-weight:700}.banner.whatif{background:#dff0e8;border:1px solid #a8cec0}
.flag{display:inline-block;padding:2px 7px;border:1px solid #d7c8b9;background:#faf3eb;margin:2px 4px 2px 0}
@media (max-width:860px){.hero{grid-template-columns:1fr}.span-7,.span-5,.span-12{grid-column:span 12}}
</style></head><body><main>
<section id="login-view" class="panel"><h1>Student Grades Portal</h1><p>View grades, try scenarios, and change your password.</p><label>Username<input id="username" autocomplete="username"></label><label>Password<input id="password" type="password" autocomplete="current-password"></label><button id="login-btn">Sign In</button><p id="login-error" class="error"></p></section>
<section id="app-view" class="hidden">
<div id="whatif-banner" class="banner whatif hidden">What-If Studio. Everything on this page is pretend and does not change your real gradebook.</div>
<div class="hero" style="margin-top:18px"><div class="panel gpa"><div class="label">GPA</div><div id="gpa-value" class="value"></div><div id="gpa-small" class="small"></div></div><div class="panel identity"><h1 id="student-name" class="strong"></h1><p id="student-course" class="meta"></p><p id="student-sections" class="meta"></p><p class="meta">Portal username: <strong id="student-username"></strong></p><div class="page-actions" style="margin-top:14px"><a href="/"><button type="button" class="ghost">Grade Overview</button></a><a href="/what-if"><button type="button" class="alt">What-If Studio</button></a><button id="logout-btn" type="button" class="ghost">Sign Out</button></div></div></div>
<div id="password-notice" class="notice hidden" style="margin-top:18px">You must change your password before using the portal normally.</div>

<div id="overview-page"><div class="grid"><div class="panel span-7"><h2>Assignments</h2><table id="assignments-table"><thead><tr><th>Assignment</th><th>Category</th><th>Current</th><th>Flags</th></tr></thead><tbody></tbody></table></div><div class="panel span-5"><h2>Improve Your Grade</h2><ul id="tips-list" class="tip-list"></ul></div></div><div class="grid"><div class="panel span-7"><h2>Category Totals</h2><table id="categories-table"><thead><tr><th>Category</th><th>Weight</th><th>Status</th><th>Score</th></tr></thead><tbody></tbody></table></div><div class="panel span-5"><h2>Password</h2><label>Current password<input id="current-password" type="password" autocomplete="current-password"></label><label>New password<input id="new-password" type="password" autocomplete="new-password"></label><button id="change-password-btn" class="alt">Change Password</button><p id="password-error" class="error"></p></div></div></div>

<div id="whatif-page" class="hidden"><div class="grid"><div class="panel span-7"><h2>Scenario Assignments</h2><p>Create pretend assignments using your real categories.</p><label>Title<input id="scenario-title" placeholder="Practice Final"></label><label>Category<select id="scenario-category"></select></label><label>Max points<input id="scenario-max" type="number" min="1" step="1" value="100"></label><label>Score<input id="scenario-score" type="number" min="0" step="0.1" value="100"></label><button id="scenario-add-btn" type="button">Add Pretend Assignment</button><table id="scenario-table" style="margin-top:14px"><thead><tr><th>Assignment</th><th>Category</th><th>Score</th><th>Remove</th></tr></thead><tbody></tbody></table></div><div class="panel span-5"><h2>Needed Score</h2><label>Assignment<select id="calculator-assignment"></select></label><label>Target GPA (%)<input id="target-score" type="number" min="0" max="100" step="0.1" value="90"></label><button id="needed-score-btn" type="button" class="ghost">Find Needed Score</button><p id="needed-score-output"></p></div></div><div class="grid"><div class="panel span-12"><h2>Scenario Category Totals</h2><table id="scenario-categories-table"><thead><tr><th>Category</th><th>Weight</th><th>Status</th><th>Scenario score</th></tr></thead><tbody></tbody></table></div></div></div>
</section>

<script>
let portalData=null,accountInfo=null,scenarioAssignments=[];const byId=id=>document.getElementById(id);const mode=location.pathname==="/what-if"?"what-if":"overview";if(mode==="what-if")document.body.classList.add("what-if");
async function api(path,opt={}){const cfg={credentials:"same-origin",...opt,headers:{"Content-Type":"application/json"}};const res=await fetch(path,cfg);const text=await res.text();let data={};if(text){try{data=JSON.parse(text)}catch(_){}}if(!res.ok)throw new Error(data.error||"Request failed");return data}
function showLogin(){byId("login-view").classList.remove("hidden");byId("app-view").classList.add("hidden")} function showApp(){byId("login-view").classList.add("hidden");byId("app-view").classList.remove("hidden");byId("overview-page").classList.toggle("hidden",mode!=="overview");byId("whatif-page").classList.toggle("hidden",mode!=="what-if");byId("whatif-banner").classList.toggle("hidden",mode!=="what-if")}
function containsFlag(flags,want){return Array.isArray(flags)&&flags.includes(want)} function curvedPercent(raw,anchor,lift){if(raw<=0)return 0;return Math.pow(raw,(100-lift)/100)*Math.pow(anchor,lift/100)} function recordPercent(item,score){if(score==null||item.maxPoints<=0||containsFlag(item.flags,"missing"))return 0;return curvedPercent((score/item.maxPoints)*100,item.anchor,item.lift)}
function assignmentPercent(item,score){if(item.schemeKey==="completion"){if(!item.passPercent||item.passPercent<=0)return recordPercent(item,score);if(score==null||item.maxPoints<=0||containsFlag(item.flags,"missing"))return 0;const raw=(score/item.maxPoints)*100;if(raw<item.passPercent)return 0;let out=100;if(containsFlag(item.flags,"redo"))out-=10;if(containsFlag(item.flags,"late"))out-=10;return Math.max(out,0)}return recordPercent(item,score)}
function assignmentHasEntry(item,score){return score!=null||(item.flags&&item.flags.length>0)} function realAssignments(){return portalData?portalData.assignments.map(item=>({...item,__scenario:false})):[]} function allAssignments(){return [...realAssignments(),...scenarioAssignments]} function categories(){return portalData?portalData.categories:[]}
function categoryResult(category,items){const related=items.filter(item=>item.categoryId===category.categoryId);const active=related.some(item=>assignmentHasEntry(item,item.score));if(!active)return {included:false,score:0,label:""};if(category.schemeKey==="total-points"){let sum=0,maxTotal=0;for(const item of related){maxTotal+=item.maxPoints;sum+=(assignmentPercent(item,item.score)/100)*item.maxPoints}const score=maxTotal>0?(sum/maxTotal)*100:0;return {included:true,score,label:score.toFixed(1)+"%"}}let total=0;for(const item of related)total+=assignmentPercent(item,item.score);const score=related.length?total/related.length:0;return {included:true,score,label:score.toFixed(1)+"%"}}
function recomputeView(){if(!portalData)return 0;let num=0,den=0,activeCount=0;for(const category of categories()){const result=categoryResult(category,allAssignments());const tableId=mode==="what-if"?"scenario-categories-table":"categories-table";const row=document.querySelector("#"+tableId+' [data-category-row="'+category.categoryId+'"] .score');const state=document.querySelector("#"+tableId+' [data-category-row="'+category.categoryId+'"] .state');if(row)row.textContent=result.label||"Not active yet";if(state)state.textContent=result.included?"Active":"Waiting for first entry";if(result.included){activeCount++;if(category.hasWeight){num+=result.score*category.weightPercent;den+=category.weightPercent}}}const weighted=den>0?num/den:0;byId("gpa-value").textContent=(den>0?weighted.toFixed(1):"0.0")+"%";byId("gpa-small").textContent=(activeCount||0)+" active categor"+(activeCount===1?"y":"ies");return weighted}
function renderHeader(){byId("student-name").textContent=portalData.firstName+" "+portalData.lastName;byId("student-course").textContent=portalData.courseName+" | "+portalData.termName;byId("student-sections").textContent="Sections: "+(portalData.sections||[]).join(", ");byId("student-username").textContent=accountInfo.username;byId("password-notice").classList.toggle("hidden",!accountInfo.mustChangePassword)}
function renderOverview(){const tbody=byId("assignments-table").querySelector("tbody");tbody.innerHTML="";for(const item of portalData.assignments){const flags=(item.flags&&item.flags.length)?item.flags.map(flag=>"<span class='flag'>"+flag+"</span>").join(""):"OK";const row=document.createElement("tr");row.innerHTML="<td>"+item.title+"</td><td>"+item.categoryName+"</td><td>"+item.currentPercentLabel+"</td><td>"+flags+"</td>";tbody.appendChild(row)}const tips=byId("tips-list");tips.innerHTML="";for(const tip of portalData.improvementTips||[]){const li=document.createElement("li");li.textContent=tip;tips.appendChild(li)}const body=byId("categories-table").querySelector("tbody");body.innerHTML="";for(const category of portalData.categories){const row=document.createElement("tr");row.setAttribute("data-category-row",category.categoryId);row.innerHTML="<td>"+category.categoryName+"</td><td>"+(category.weightLabel||"")+"</td><td class='state'>"+(category.included?"Active":"Waiting for first entry")+"</td><td class='score'>"+(category.scoreLabel||"Not active yet")+"</td>";body.appendChild(row)}}
function renderWhatIf(){const select=byId("scenario-category");select.innerHTML="";for(const category of categories()){const option=document.createElement("option");option.value=category.categoryId;option.textContent=category.categoryName;select.appendChild(option)}const body=byId("scenario-categories-table").querySelector("tbody");body.innerHTML="";for(const category of categories()){const row=document.createElement("tr");row.setAttribute("data-category-row",category.categoryId);row.innerHTML="<td>"+category.categoryName+"</td><td>"+(category.weightLabel||"")+"</td><td class='state'>"+(category.included?"Active":"Waiting for first entry")+"</td><td class='score'>"+(category.scoreLabel||"Not active yet")+"</td>";body.appendChild(row)}refreshScenarioTable();refreshCalculatorOptions()}
function refreshScenarioTable(){const body=byId("scenario-table").querySelector("tbody");body.innerHTML="";scenarioAssignments.forEach(item=>{const row=document.createElement("tr");row.innerHTML="<td>"+item.title+"</td><td>"+item.categoryName+"</td><td>"+item.score+" / "+item.maxPoints+"</td><td><button type='button' class='ghost' data-remove-scenario='"+item.assignmentId+"'>Remove</button></td>";body.appendChild(row)});document.querySelectorAll("[data-remove-scenario]").forEach(btn=>btn.addEventListener("click",()=>{const id=Number(btn.getAttribute("data-remove-scenario"));scenarioAssignments=scenarioAssignments.filter(item=>item.assignmentId!==id);refreshScenarioTable();refreshCalculatorOptions();recomputeView()}))}
function refreshCalculatorOptions(){const select=byId("calculator-assignment");if(!select)return;select.innerHTML="";for(const item of allAssignments()){const option=document.createElement("option");option.value=(item.__scenario?"s":"r")+item.assignmentId;option.textContent=item.title+" ("+item.categoryName+")";select.appendChild(option)}}
function addScenario(){const categoryId=Number(byId("scenario-category").value);const category=portalData.categories.find(item=>item.categoryId===categoryId);if(!category)return;scenarioAssignments.push({assignmentId:Date.now()+Math.floor(Math.random()*1000),title:(byId("scenario-title").value||"Pretend Assignment").trim(),categoryId,categoryName:category.categoryName,maxPoints:Math.max(1,Number(byId("scenario-max").value)||100),schemeKey:category.schemeKey,passPercent:category.defaultPassPercent>0?category.defaultPassPercent:null,anchor:100,lift:0,score:Math.max(0,Number(byId("scenario-score").value)||0),flags:[],currentPercent:0,currentPercentLabel:"",__scenario:true});byId("scenario-title").value="";refreshScenarioTable();refreshCalculatorOptions();recomputeView()}
function findNeededScore(){const selected=byId("calculator-assignment").value;const target=Number(byId("target-score").value);const item=allAssignments().find(entry=>((entry.__scenario?"s":"r")+entry.assignmentId)===selected);if(!item||!Number.isFinite(target)){byId("needed-score-output").textContent="Choose an assignment and target first.";return}const original=item.score;let low=0,high=item.maxPoints,answer=null;for(let i=0;i<35;i++){const mid=(low+high)/2;item.score=mid;const total=recomputeView();if(total>=target){answer=mid;high=mid}else{low=mid}}item.score=original;recomputeView();byId("needed-score-output").textContent=answer==null?"Even with full marks here, that target GPA is out of reach.":"Needed on "+item.title+": "+answer.toFixed(1)+" / "+item.maxPoints}
function render(){showApp();renderHeader();renderOverview();if(mode==="what-if")renderWhatIf();recomputeView()}
async function loadPortal(){accountInfo=await api("/api/me");portalData=await api("/api/grades");render()}
byId("login-btn").addEventListener("click",async()=>{byId("login-error").textContent="";try{await api("/api/login",{method:"POST",body:JSON.stringify({username:byId("username").value,password:byId("password").value})});await loadPortal()}catch(err){byId("login-error").textContent=err.message}});byId("change-password-btn").addEventListener("click",async()=>{byId("password-error").textContent="";try{await api("/api/change-password",{method:"POST",body:JSON.stringify({currentPassword:byId("current-password").value,newPassword:byId("new-password").value})});byId("current-password").value="";byId("new-password").value="";accountInfo.mustChangePassword=false;byId("password-notice").classList.add("hidden")}catch(err){byId("password-error").textContent=err.message}});if(byId("scenario-add-btn"))byId("scenario-add-btn").addEventListener("click",addScenario);if(byId("needed-score-btn"))byId("needed-score-btn").addEventListener("click",findNeededScore);byId("logout-btn").addEventListener("click",async()=>{await api("/api/logout",{method:"POST"});portalData=null;accountInfo=null;scenarioAssignments=[];showLogin()});loadPortal().catch(()=>showLogin());
</script></main></body></html>`))
